Try updating Java to 17
I have a feeling this might fix an error that updating languagetool has
caused:

```
java.lang.IncompatibleClassChangeError: Class com.google.common.base.Suppliers$SupplierOfInstance does not implement the requested interface java.util.function.Supplier
```

When I google that error I get mentions of guava (which languagetool
depends on), plus I know Java 11 was the release where a lot of the
functional interfaces were new. Also, [the changelog for
languagetool](https://languagetool.org/download/CHANGES.md) mentions a
need to update to Java 17 from version 6.6: maybe they’re mistaken and
the update is needed a version earlier?